language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.1

matrix:
  fast_finish: true
  include:
  - php: 7.1
    env: PHPSTAN=1
  - php: 7.1
    env: CODING_STANDARD=1
  - php: 7.1
    env: COVERAGE="--coverage-clover tests/coverage.xml"

install:
  - if [ "$PHPSTAN" = "1" ]; then composer require --dev --no-update phpstan/phpstan-shim:^0.7; fi
  - travis_retry composer update --no-interaction --no-suggest --no-progress --prefer-stable
  - travis_retry composer create-project --no-interaction jakub-onderka/php-parallel-lint /tmp/php-parallel-lint
  - if [ "$COVERAGE" != "" ]; then travis_retry wget -O /tmp/coveralls.phar https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar; fi

script:
  - php vendor/bin/phpunit $COVERAGE -c tests/phpunit.xml tests
  - php /tmp/php-parallel-lint/parallel-lint.php -e php,phpt --exclude vendor .
  - if [ "$PHPSTAN" = "1" ]; then php vendor/phpstan/phpstan-shim/phpstan.phar analyse --ansi --no-progress -l7 -c phpstan.neon GrandMediaCodingStandard tests; fi
  - if [ "$CODING_STANDARD" = "1" ]; then php vendor/bin/phpcs --standard=ruleset.xml --encoding=utf-8 -sp GrandMediaCodingStandard tests; fi

after_script:
  - if [ "$COVERAGE" != "" ]; then php /tmp/coveralls.phar --verbose --config tests/.coveralls.yml || true; fi

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
